import java.time.LocalDate

/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {
    String getGreeting() {
        return 'Hello world.'
    }

    LocalDate nowIsh() {
        LocalDate.now()
    }

    static void main(String[] args) {
        println new App().greeting
    }
}
