/*
 * This Spock specification was generated by the Gradle 'init' task.
 */

import org.junit.runner.RunWith
import spock.lang.Specification
import dev.sarek.agent.mock.MockFactory

import java.time.LocalDate
import java.time.Month

import static net.bytebuddy.matcher.ElementMatchers.named

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }


    def "mock LocalDate.now()"() {
        setup:
        def app = new App()

        and:
        MockFactory<LocalDate> mockFactory = MockFactory
                .forClass(LocalDate.class)
                .mockStatic(
                        named("now"),
                        { method, args -> false },
                        { method, args, proceedMode, returnValue, throwable -> LocalDate.of(2019, 1, 1) }
                )
                .build()

        when:
        def result = app.nowIsh()

        then:
        result.year == 2019
        result.monthValue == 1
        result.dayOfMonth == 1

    }
}
